### ISSUE TITLE
Replace visited instructions with ancestry sets

### ISSUE THREAD

**Issue by DrRataplan** [bwrrp/whynot.js#34]
The implementation of cycle detection using the visited instructions inside Trace is computational and memory heavy. This can be optimized using a DisjointSet data structure.

**Comment by bwrrp** [comment]
Looking into this and the PR a bit more, it seems that we also merge visited instructions into descendant traces in the current implementation. I'm not sure why this does not trigger the same bug where a cycle is detected where there is none...

**Comment by bwrrp** [comment]
Ah, never mind, we currently only propagate what has been visited by the new prefix, but the disjoint sets approach would propagate all visits from that point on as well, leading to normal merges being seen as cycles...
